# -*- coding: utf-8 -*-
"""atividade-pratica-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkVpdLTvfF0J8cXEiopQFGAaZdLHGg9W
"""

def calculadora():
    while True:
        try:
            num1 = int(input("Digite o primeiro número: "))
            num2 = int(input("Digite o segundo número: "))
            operacao = input("Digite a operação (+, -, *, /): ")

            if operacao == '+':
                resultado = num1 + num2
            elif operacao == '-':
                resultado = num1 - num2
            elif operacao == '*':
                resultado = num1 * num2
            elif operacao == '/':
                if num2 == 0:
                    raise ZeroDivisionError("Divisão por zero não é permitida.")
                resultado = num1 / num2
            else:
                raise ValueError("Operação inválida.")

            print(f"O resultado de {num1} {operacao} {num2} é: {resultado}")
            break

        except ValueError as ve:
            print(f"Erro: {ve}. Tente novamente.")
        except ZeroDivisionError as zde:
            print(f"Erro: {zde}. Tente novamente.")
        except Exception as e:
            print(f"Erro inesperado: {e}. Tente novamente.")

calculadora()