# -*- coding: utf-8 -*-
"""atividade-pratica-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12v6IR21baixOR_YsyIPu6xQZ_Cn2JER9
"""

# Crie um programa que permita a um professor registrar as notas de uma turma. O programa deve continuar solicitando notas até que o professor digite 'fim'. Notas válidas são de 0 a 10. O programa deve ignorar notas inválidas e continuar solicitando. No final, deve exibir a média da turma.

def registrar_notas():
    notas = []

    while True:
        entrada = input("Digite a nota do aluno (ou 'fim' para encerrar): ").strip()

        if entrada.lower() == 'fim':
            break

        try:
            nota = float(entrada)
            if 0 <= nota <= 10:
                notas.append(nota)
            else:
                print("Nota inválida. Digite um valor entre 0 e 10.")
        except ValueError:
            print("Entrada inválida. Digite um número ou 'fim'.")

    if notas:
        media = sum(notas) / len(notas)
        print(f"Média da turma: {media:.2f}")
    else:
        print("Nenhuma nota válida foi registrada.")

    print(notas)
    print("Programa encerrado.")

# Executa o programa
registrar_notas()